### PR TITLE
Feat/explorer UI constants Rewrite

### PR DESCRIPTION
**Pull request by Defi-Moses**
**Description**
This PR refactors all of the synapse explorer to use the same constants folder used in the synapse interface and elsewhere. It deprecates files like basic.ts in favor of bridgeable.ts etc. 

**Additional context**
In the process fixed a few bugs (certain images not loading, USDC.e vs USDC).

**Metadata**
- Fixes #[Link to Issue]

## Summary by CodeRabbit

- **New Features**
  - Introduced new smart contract interface definitions for enhanced blockchain interactions.
  - Added new constants and utility functions for improved chain and token identification.

- **Refactor**
  - Updated import paths for better project structure and maintainability.
  - Refined logic for accessing chain and token information to ensure consistency and reliability.

- **Bug Fixes**
  - Removed case sensitivity from token address assignments to prevent mismatch errors.
  - Implemented null checks to avoid potential crashes when accessing token and chain data.

- **Documentation**
  - Added detailed comments for new constants and functions to facilitate easier understanding and usage.

- **Style**
  - Adjusted styles for chain and token imagery to align with updated logic and ensure a cohesive user interface.

b6b92b8933f301b198bab5d4fb8b963b250cb92b: [explorer-ui preview link ](https://sanguine-c8k8wruau-synapsecns.vercel.app)
f6c9099f46b44430708354360a15dba36aa022f8: [explorer-ui preview link ](https://sanguine-meik8z22j-synapsecns.vercel.app)
1869f52e287f7993ac4d77dc791a2b53b41f7ddf: [explorer-ui preview link ](https://sanguine-7w51weusv-synapsecns.vercel.app)
1869f52e287f7993ac4d77dc791a2b53b41f7ddf: [synapse-interface preview link ](https://sanguine-synapse-interface-fmudp973z-synapsecns.vercel.app)
d7fab0f8cd6870991390113e29cd3f5614cc3199: [explorer-ui preview link ](https://sanguine-bbbd2ao8u-synapsecns.vercel.app)
d7fab0f8cd6870991390113e29cd3f5614cc3199: [synapse-interface preview link ](https://sanguine-synapse-interface-9r7r7rofo-synapsecns.vercel.app)
be4a55bfe13ec6a23731fe8e3de8bc81027e016d: [explorer-ui preview link ](https://sanguine-evsf873xt-synapsecns.vercel.app)
063b2066bac2f1c6a995cd9599ba54f040b0ddf6: [explorer-ui preview link ](https://sanguine-k6onnxqhv-synapsecns.vercel.app)
a32dd2e59f3ea2c62bca51b9d4a33a603977cfa7: [explorer-ui preview link ](https://sanguine-pmlh9dbgz-synapsecns.vercel.app)
d91b36deeef62f6b7868b0c111cdecd467ccc855: [explorer-ui preview link ](https://sanguine-hh7thp9bq-synapsecns.vercel.app)
3749ece65c4032424e160f3fefe6fcded083c93b: [explorer-ui preview link ](https://sanguine-dgdqyi499-synapsecns.vercel.app)
8bf254c5e930b8a0a6d0ea0a45001d96447ed5f1: [explorer-ui preview link ](https://sanguine-7bwqwb2t4-synapsecns.vercel.app)
8bf254c5e930b8a0a6d0ea0a45001d96447ed5f1: [synapse-interface preview link ](https://sanguine-synapse-interface-98zullemf-synapsecns.vercel.app)

### CODE REVIEW

**Comment by trajan0x** [comment]
yarn pls

**Review by bigboydiamonds — APPROVED** [review]

**Review by nautsimon — APPROVED** [review]
this is sick, lfg

**Comment by trajan0x** [comment]
Are we duplicating the icons?

**Comment by Defi-Moses** [comment]
> Are we duplicating the icons?

No, We delete all of the icons in the /icons folder and add them in sorted folders to follow the pattern in [synapse-interface](https://github.com/synapsecns/sanguine/tree/master/packages/synapse-interface/assets)

**Comment by trajan0x** [comment]
Can we just symlink to synapseinterface?

**Comment by Defi-Moses** [comment]
> Can we just symlink to synapseinterface?

Thats the long term plan. Looking to get this merged and then I can merge in the npm package synapse-constants that will live at packages/synapse-constants (This is 90% finished).

**Pull request merged**
