### PR TITLE
applyBridgeSlippage() applySwapSlippage() applied

### PR DESCRIPTION
**Pull request by bigboydiamonds**
## Summary by CodeRabbit

- **New Features**
	- Enhanced slippage handling for bridge transactions using `synapseSDK.applyBridgeSlippage`.
	- Improved slippage calculations for swaps with `synapseSDK.applySwapSlippage`.

- **Refactor**
	- Streamlined slippage logic in bridge and swap components for better performance and accuracy.

f192e69858a3514d8d23a1aed8fa40f72df5332c: [synapse-interface preview link ](https://sanguine-synapse-interface-cpd17w7vp-synapsecns.vercel.app)
f473bf9eb23687a821e73e447b7a1b5daa005257: [synapse-interface preview link ](https://sanguine-synapse-interface-qdy996ts5-synapsecns.vercel.app)
6d5263a8cc7ea68e04c1de58127669a260f16d39: [synapse-interface preview link ](https://sanguine-synapse-interface-3p683h0jf-synapsecns.vercel.app)

### CODE REVIEW

**Comment by ChiTimesChi** [comment]
> Cannot read properties of undefined (reading 'swapAdapter')

This error is thrown on a swap attempt in this test build, figuring out if this is present in master (not seeing this in production right now)

**Review by ChiTimesChi — APPROVED** [review]
LGTM, the fix above appears to be working.

**Comment by ChiTimesChi** [comment]
Actually, let's remove unused `subtractSlippage` imports?
This + the same in two other affected files.
https://github.com/synapsecns/sanguine/blob/3fe9dc7b909948c3466f68296cf40f7797074c1e/packages/synapse-interface/pages/state-managed-bridge/index.tsx#L28

Can't rip this function entirely yet, as it's still used for slippage on add/remove liquidity operations. Opened an issue for updating the SDK: 
- #1878

**Comment by bigboydiamonds** [comment]
> Actually, let's remove unused `subtractSlippage` imports? This + the same in two other affected files.
> 
> https://github.com/synapsecns/sanguine/blob/3fe9dc7b909948c3466f68296cf40f7797074c1e/packages/synapse-interface/pages/state-managed-bridge/index.tsx#L28
> 
> Can't rip this function entirely yet, as it's still used for slippage on add/remove liquidity operations. Opened an issue for updating the SDK:
> 
> * [[SDK] Expose better wrappers for pool liquidity operations #1878](https://github.com/synapsecns/sanguine/issues/1878)

Cleaned imports in https://github.com/synapsecns/sanguine/pull/1877/commits/aca4a49cfca76741acac012f4ebb360f24943bc0

**Pull request merged**
