### PR TITLE
SDK: cleanup

### PR DESCRIPTION
**Pull request by ChiTimesChi**
**Description**
Major refactor of Router SDK in preparation for RouterV2 and external Router Adapters.

High level overview of the changes:
- Introduced `Router` class that abstracts away the contract interactions and normalizes the data structures that different contracts are using, so that the rest of SDK (and its consumers) are dealing with unified types like `Query`.
  - `SynapseRouter` and `SynapseCCTPRouter` inherit from it to add support for corresponding contracts.
- Introduced `RouterSet` class that handles the interactions with Routers on a few chains (such as bridge quote).
  - `SynapseRouterSet` and `SynapseCCTPRouterSet` inherit from it to add support for corresponding contract sets.
- The SDK functions are split into a few types and implemented in `src/operations` to increase readability:
  - `src/operations/bridge` for bridging and bridge quoting,
  - `src/operations/pool` for pool inspection,
  - `src/operations/swap` for swapping and swap quoting.
- Cleaned up and adapted the test suite, added a bit more coverage.
  - Common test values now reside in `src/constants/testValues.ts`

The changes were done in a non-breaking way, so that the SDK consumers could update w/o adjusting their code.

3fcf49bb63fecae9bf2e2cfa7489547e832e6d79: [synapse-interface preview link ](https://sanguine-synapse-interface-2d33bj2wp-synapsecns.vercel.app)
ef98f149853dda4e7a8cfcf69c10bebcda9926fc: [synapse-interface preview link ](https://sanguine-synapse-interface-cbt3yozme-synapsecns.vercel.app)
2c8fed5e3403070f500c4ae0cbbf190cf2b71ced: [synapse-interface preview link ](https://sanguine-synapse-interface-ge16lyyoq-synapsecns.vercel.app)

### CODE REVIEW

**Comment by trajan0x** [comment]
@ChiTimesChi im going to make a quick change to the readme of `packages/synapse-interface` so we can get a version of this on vercel

**Comment by bigboydiamonds** [comment]
Spinning up vercel deployment using sdk via local package link: https://github.com/synapsecns/sanguine/pull/1356

**Comment by trajan0x** [comment]
Ty @bigboydiamonds

**Comment by ChiTimesChi** [comment]
Closing this one to get a PR with @coderabbitai

**Pull request closed without merging**
